---
- set_fact:
    bviktor_file_changed_before_checksum: "{{ file_changed_stat.stat.checksum | default('') }}"

- debug:
    msg: "Checksum: {{ bviktor_file_changed_before_checksum }}"
  when: eff_verbose

- set_fact:
    file_changed:
      changed: false
